name: Deploy to GitHub Pages

on:
  # Wird bei jedem Push auf den main Branch ausgelöst
  push:
    branches: ["main"]
  # Ermöglicht manuelles Auslösen des Workflows über die Actions-Tab
  workflow_dispatch:

permissions:
  contents: read # Erlaubt das Lesen des Repository-Codes
  pages: write # Erlaubt das Schreiben auf GitHub Pages
  id-token: write # Benötigt für sichere Deployments

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest # Verwendet Ubuntu als Betriebssystem
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build